CREATE DATABASE QUANLYVATLIEU;
USE QUANLYVATLIEU;

CREATE TABLE VATLIEU(
                        ID INT PRIMARY KEY AUTO_INCREMENT,
                        MA_VATLIEU VARCHAR(255) NOT NULL ,
                        TEN_VATLIEU VARCHAR(255) NOT NULL ,
                        DVT VARCHAR(255) NOT NULL ,
                        GIATIEN DOUBLE
);

INSERT INTO VATLIEU(MA_VATLIEU, TEN_VATLIEU, DVT, GIATIEN)
VALUES('VL01','BÁT','CÁI',20),
      ('VL02','ĐĨA','CÁI',50),
      ('VL03','ĐŨA','ĐÔI',10),
      ('VL04','THÌA','CÁI',15),
      ('VL05','DĨA','CÁI',10);

CREATE TABLE NHACUNGCAP(
                           ID INT PRIMARY KEY AUTO_INCREMENT,
                           MA_NHACUNGCAP VARCHAR(255) NOT NULL ,
                           TEN_NHACUNGCAP VARCHAR(255) NOT NULL ,
                           DIACHI VARCHAR(255) NOT NULL ,
                           SDT VARCHAR(255) NOT NULL
);

INSERT INTO NHACUNGCAP(MA_NHACUNGCAP, TEN_NHACUNGCAP, DIACHI, SDT)
VALUES ('CH01','NCC1','HA NOI','0799.999.666'),
       ('CH02','NCC2','HAI DUONG','0374.747.474'),
       ('CH03','NCC3','BAC NINH','0868.666.888');

CREATE TABLE KHO(
                    ID INT PRIMARY KEY AUTO_INCREMENT,
                    VATTU_ID INT,
                    SOLUONGDAU INT NOT NULL ,
                    TONGSOLUONGNHAP INT NOT NULL ,
                    TONGSOLUONGXUAT INT NOT NULL ,
                    FOREIGN KEY (VATTU_ID) REFERENCES VATLIEU(ID)
);

INSERT INTO KHO(VATTU_ID, SOLUONGDAU, TONGSOLUONGNHAP, TONGSOLUONGXUAT)
VALUES (1,500,1000,1200),
       (1,300,1500,1000),
       (2,400,600,800),
       (2,200,1000,700),
       (3,1000,1000,1300),
       (3,700,1500,1150),
       (4,800,500,300),
       (4,1000,200,400),
       (5,400,150,200),
       (5,350,150,300);

CREATE TABLE DONHANG(
                        ID INT PRIMARY KEY AUTO_INCREMENT,
                        MA_DONHANG VARCHAR(255) NOT NULL ,
                        NGAYDATHANG DATE NOT NULL ,
                        NHACUNGCAP_ID INT,
                        FOREIGN KEY (NHACUNGCAP_ID) REFERENCES NHACUNGCAP(ID)
);

INSERT INTO DONHANG(MA_DONHANG, NGAYDATHANG, NHACUNGCAP_ID)
VALUES ('MH01','2021-05-19',1),
       ('MH02','2021-06-23',2),
       ('MH03','2021-06-24',3);

CREATE TABLE PHIEUNHAP(
                          ID INT PRIMARY KEY AUTO_INCREMENT,
                          MA_PHIEUNHAP VARCHAR(255) NOT NULL ,
                          NGAYNHAP DATE NOT NULL ,
                          DONHANG_ID INT,
                          FOREIGN KEY (DONHANG_ID) REFERENCES DONHANG(ID)
);

INSERT INTO PHIEUNHAP(MA_PHIEUNHAP, NGAYNHAP, DONHANG_ID)
VALUES ('PN01','2021-05-21',1),
       ('PN02','2021-07-01',2),
       ('PN03','2021-06-28',3);

CREATE TABLE PHIEUXUAT(
                          ID INT PRIMARY KEY AUTO_INCREMENT,
                          MA_PHIEUXUAT VARCHAR(255) NOT NULL ,
                          NGAYXUAT DATE NOT NULL ,
                          TEN_KHACHHANG VARCHAR(255) NOT NULL
);

INSERT INTO PHIEUXUAT(MA_PHIEUXUAT, NGAYXUAT, TEN_KHACHHANG)
VALUES ('PX01','2021-07-05','NGUYEN SON D'),
       ('PX02','2021-08-25','TRAN PHUONG H'),
       ('PX03','2021-08-27','VU MINH T');

CREATE TABLE CTDONHANG(
                          ID INT PRIMARY KEY AUTO_INCREMENT,
                          DONHANG_ID INT NOT NULL ,
                          VATTU_ID INT NOT NULL ,
                          SOLUONGDAT INT NOT NULL ,
                          FOREIGN KEY (DONHANG_ID) REFERENCES DONHANG(ID),
                          FOREIGN KEY (VATTU_ID) REFERENCES VATLIEU(ID)
);

INSERT INTO CTDONHANG(DONHANG_ID, VATTU_ID, SOLUONGDAT)
VALUES (1,1,500),
       (1,2,500),
       (2,5,300),
       (2,3,400),
       (3,4,200),
       (3,2,200);

CREATE TABLE CTPHIEUNHAP(
                            ID INT PRIMARY KEY AUTO_INCREMENT,
                            PHIEUNHAP_ID INT NOT NULL ,
                            VATTU_ID INT NOT NULL ,
                            SOLUONGNHAP INT NOT NULL ,
                            DONGIANHAP DOUBLE NOT NULL ,
                            GHICHU VARCHAR(255) NOT NULL ,
                            FOREIGN KEY (PHIEUNHAP_ID) REFERENCES PHIEUNHAP(ID),
                            FOREIGN KEY (VATTU_ID) REFERENCES  VATLIEU(ID)
);

INSERT INTO CTPHIEUNHAP(PHIEUNHAP_ID, VATTU_ID, SOLUONGNHAP, DONGIANHAP, GHICHU)
VALUES (1,1,500,50,'NHAP 500 CAI DIA'),
       (1,2,300,20,'NHAP 300 CAI BAT'),
       (2,3,800,10,'NHAP 800 DOI DUA'),
       (2,5,400,10,'NHAP 400 CAI DIA'),
       (3,2,300,20,'NHAP 300 CAI BAT'),
       (3,4,250,15,'NHAP 250 CAI THIA');

CREATE TABLE CTPHIEUXUAT(
                            ID INT PRIMARY KEY AUTO_INCREMENT,
                            PHIEUXUAT_ID INT NOT NULL ,
                            VATTU_ID INT NOT NULL ,
                            SOLUONGXUAT INT NOT NULL ,
                            DONGIAXUAT DOUBLE NOT NULL ,
                            GHICHU VARCHAR(255),
                            FOREIGN KEY (PHIEUXUAT_ID) REFERENCES PHIEUNHAP(ID),
                            FOREIGN KEY (VATTU_ID) REFERENCES VATLIEU(ID)
);

INSERT INTO CTPHIEUXUAT(PHIEUXUAT_ID, VATTU_ID, SOLUONGXUAT, DONGIAXUAT,GHICHU)
VALUES (1,1,700,60,'XUAT 700 CAI DIA'),
       (1,2,500,25,'NHAP 300 CAI BAT'),
       (2,3,750,12.5,'XUAT 750 DOI DUA'),
       (2,5,500,11.5,'XUAT 500 CAI DIA'),
       (3,2,200,25,'XUAT 200 CAI BAT'),
       (3,4,400,17,'XUAT 250 CAI THIA');

# LAY RA SO PHIEU NHAP, MA VAT TU, SO LUONG NHAP, DON GIA NHAP, THANH TIEN
SELECT MA_PHIEUNHAP AS 'SO PHIEU NHAP', MA_VATLIEU AS 'MA VAT TU',
       SOLUONGNHAP AS 'SO LUONG NHAP', DONGIANHAP AS 'DON GIA',
       SOLUONGNHAP*CTPHIEUNHAP.DONGIANHAP AS 'THANH TIEN'
FROM CTPHIEUNHAP JOIN VATLIEU V on CTPHIEUNHAP.VATTU_ID = V.ID
                 JOIN PHIEUNHAP P on CTPHIEUNHAP.PHIEUNHAP_ID = P.ID;

# LAY RA SO PHIEU NHAP HANG, SO DON HANG,TEN VAT TU, SO LUONG NHAP, DON GIA NHAP, THANH TIEN
SELECT MA_PHIEUNHAP AS 'SO PHIEU NHAP', MA_DONHANG AS 'MA DON HANG',
       TEN_VATLIEU AS 'TEN VAT TU', SOLUONGNHAP AS 'SO LUONG NHAP',
       DONGIANHAP AS 'DON GIA',SOLUONGNHAP*CTPHIEUNHAP.DONGIANHAP AS 'THANH TIEN'
FROM CTPHIEUNHAP JOIN PHIEUNHAP P on P.ID = CTPHIEUNHAP.PHIEUNHAP_ID
                 JOIN VATLIEU V on CTPHIEUNHAP.VATTU_ID = V.ID JOIN DONHANG D on P.DONHANG_ID = D.ID;

# LAY RA SO PHIEU NHAP HANG, NGAY NHAP HANG, SO DON DAT HANG, MA VAT TU, TEN VAT TU,SO LUONG NHAP,
# DON GIA NHAP, THANH TIEN
SELECT MA_PHIEUNHAP AS 'SO PHIEU NHAP',NGAYNHAP AS 'NGAY NHAP HANG',
       MA_DONHANG AS 'SO DON HANG', MA_VATLIEU AS 'MA VAT TU',
       TEN_VATLIEU AS 'TEN VAT LIEU', SOLUONGNHAP AS 'SO LUONG NHAP',
       DONGIANHAP AS 'DON GIA NHAP', SOLUONGNHAP*CTPHIEUNHAP.DONGIANHAP AS 'THANH TIEN'
FROM CTPHIEUNHAP JOIN PHIEUNHAP P on CTPHIEUNHAP.PHIEUNHAP_ID = P.ID
                 JOIN DONHANG D on P.DONHANG_ID = D.ID JOIN VATLIEU V on CTPHIEUNHAP.VATTU_ID = V.ID;

# số phiếu nhập hàng, ngày nhập hàng, số đơn đặt hàng, mã nhà cung cấp, mã vật tư, tên vật tư, số lượng nhập, đơn giá nhập, thành tiền nhập.
SELECT MA_PHIEUNHAP AS 'SO PHIEU NHAP', NGAYNHAP AS 'NGAY NHAP',
       MA_DONHANG AS 'SO DON HANG', MA_NHACUNGCAP AS 'MA NHA CUNG CAP',
       MA_VATLIEU AS 'MA VAT LIEU', TEN_VATLIEU AS 'TEN VAT LIEU',
       SOLUONGNHAP AS 'SO LUONG NHAP', DONGIANHAP AS 'DON GIA', SOLUONGNHAP*CTPHIEUNHAP.DONGIANHAP AS 'THANH TIEN'
FROM CTPHIEUNHAP JOIN VATLIEU V on CTPHIEUNHAP.VATTU_ID = V.ID
JOIN PHIEUNHAP P on CTPHIEUNHAP.PHIEUNHAP_ID = P.ID JOIN DONHANG D on P.DONHANG_ID = D.ID
JOIN NHACUNGCAP N on D.NHACUNGCAP_ID = N.ID;

# số phiếu nhập hàng, mã vật tư, số lượng nhập, đơn giá nhập, thành tiền nhập. Và chỉ liệt kê các chi tiết nhập có số lượng nhập > 300.
SELECT MA_PHIEUNHAP AS 'SO PHIEU NHAP', MA_VATLIEU AS 'MA VAT TU', SOLUONGNHAP AS 'SO LUONG NHAP',
       DONGIANHAP AS 'DON GIA',SOLUONGNHAP*CTPHIEUNHAP.DONGIANHAP AS 'THANH TIEN'
FROM CTPHIEUNHAP JOIN PHIEUNHAP P on CTPHIEUNHAP.PHIEUNHAP_ID = P.ID
                 JOIN VATLIEU V on CTPHIEUNHAP.VATTU_ID = V.ID WHERE SOLUONGNHAP >300;

# số phiếu nhập hàng, mã vật tư, tên vật tư, số lượng nhập, đơn giá nhập, thành tiền nhập. Và chỉ liệt kê các chi tiết nhập vật tư có đơn vị tính là Bộ.
SELECT MA_PHIEUNHAP AS 'SO PHIEU NHAP', MA_VATLIEU AS 'MA VAT TU', TEN_VATLIEU AS 'TEN VAT TU',
       DONGIANHAP AS 'DON GIA NHAP', SOLUONGNHAP AS 'SO LUONG NHAP', DONGIANHAP*CTPHIEUNHAP.SOLUONGNHAP AS 'THANH TIEN'
FROM CTPHIEUNHAP JOIN PHIEUNHAP P on CTPHIEUNHAP.PHIEUNHAP_ID = P.ID
JOIN VATLIEU V on CTPHIEUNHAP.VATTU_ID = V.ID WHERE DVT = 'DOI';

# số phiếu xuất hàng, mã vật tư, số lượng xuất, đơn giá xuất, thành tiền xuất
SELECT MA_PHIEUXUAT AS 'SO PHIEU XUAT', MA_VATLIEU AS 'MA VAT LIEU', SOLUONGXUAT AS 'SO LUONG XUAT',
       DONGIAXUAT AS 'DON GIA XUAT', SOLUONGXUAT*CTPHIEUXUAT.DONGIAXUAT AS 'THANH TIEN'
FROM CTPHIEUXUAT JOIN PHIEUXUAT P on CTPHIEUXUAT.PHIEUXUAT_ID = P.ID
                 JOIN VATLIEU V on CTPHIEUXUAT.VATTU_ID = V.ID;

# số phiếu xuất hàng, mã vật tư, tên vật tư, số lượng xuất, đơn giá xuất.
SELECT MA_PHIEUXUAT AS 'SO PHIEU XUAT', MA_VATLIEU AS 'MA VAT LIEU',TEN_VATLIEU AS 'TEN VAT LIEU',
       SOLUONGXUAT AS 'SO LUONG XUAT',DONGIAXUAT AS 'DON GIA XUAT'
FROM CTPHIEUXUAT JOIN PHIEUXUAT P on CTPHIEUXUAT.PHIEUXUAT_ID = P.ID JOIN VATLIEU V on CTPHIEUXUAT.VATTU_ID = V.ID;

# số phiếu xuất hàng, tên khách hàng, mã vật tư, tên vật tư, số lượng xuất, đơn giá xuất.
SELECT MA_PHIEUXUAT AS 'SO PHIEU XUAT',TEN_KHACHHANG AS 'TEN KHACH HANG',
       MA_VATLIEU AS 'MA VAT LIEU',TEN_VATLIEU AS 'TEN VAT LIEU',
       SOLUONGXUAT AS 'SO LUONG XUAT',DONGIAXUAT AS 'DON GIA XUAT'
FROM CTPHIEUXUAT JOIN PHIEUXUAT P on CTPHIEUXUAT.PHIEUXUAT_ID = P.ID
JOIN VATLIEU V on CTPHIEUXUAT.VATTU_ID = V.ID;